name: Latest blog post workflow
on:
  schedule: # 1時間ごとに実行
    - cron: '0 * * * *'
  workflow_dispatch: # 手動実行ボタンを表示

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://zenn.dev/shayate811/feed"
          max_post_count: 5
          date_format: "yyyy/mm/dd"
          template: "$newline| $date | [$title]($url) |"
