name: WakaTime Readme

on:
  schedule:
    # 毎日 日本時間 0:00 (UTC 15:00) に実行
    - cron: '0 15 * * *'
  workflow_dispatch: # 手動実行ボタンも有効化

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/wakatime-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
